# playbooks/install-packages.yml
---
- name: Install packages on Ubuntu WSL
  hosts: all
  become: yes
  gather_facts: yes
  
  vars:
    # Define your packages here
    essential_packages:
      - curl
      - wget
      - git
      - vim
      - htop
      - tree
      - unzip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - zsh
      - jq
    
    development_packages:
      - build-essential
      - docker.io

    optional_packages: []
    
    # Set which package groups to install
    install_essential: true
    install_development: true
    install_optional: false
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: ['always']
    
    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags: ['upgrade']
    
    - name: Install essential packages
      apt:
        name: "{{ essential_packages }}"
        state: present
      when: install_essential | bool
      tags: ['essential']
    
    - name: Install development packages
      apt:
        name: "{{ development_packages }}"
        state: present
      when: install_development | bool
      tags: ['development']
    
    - name: Install optional packages
      apt:
        name: "{{ optional_packages }}"
        state: present
      when: install_optional | bool
      tags: ['optional']

    - name: Chezmoi Install
      block:
        - name: Fetch Chezmoi Deb
          get_url:
            url: https://github.com/twpayne/chezmoi/releases/download/v2.63.1/chezmoi_2.63.1_linux_amd64.deb
            dest: /tmp/chezmoi_2.63.1_linux_amd64.deb
            checksum: sha256:158e45e5c3338cefb0dd8f76b2ea871c9c297f45d55fedb542c11879922e5d36
        - name: Install Chezmoi Deb
          ansible.builtin.apt:
            deb: /tmp/chezmoi_2.63.1_linux_amd64.deb
            state: present
          become: true
        - name: Remove Chezmoi Deb
          file:
            path: /tmp/chezmoi_2.63.1_linux_amd64.deb
            state: absent
      rescue:
        - name: Chezmoi Install Failure
          debug: msg="Chezmoi Installation Failure"
    
    - name: Clean up package cache
      apt:
        autoclean: yes
        autoremove: yes
      tags: ['cleanup']
