# playbooks/install-packages.yml
---
- name: Install packages on Ubuntu WSL
  hosts: all
  become: yes
  gather_facts: yes
  
  vars:
    # Define your packages here
    essential_packages:
      - curl
      - wget
      - git
      - vim
      - htop
      - tree
      - unzip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - zsh
      - jq
      - chromium-browser
      - snapd
    
    development_packages:
      - build-essential
      - docker.io

    snaps_sandbox:
      - vale

    snaps_classic:
      - chezmoi

    optional_packages: []
    
    # Set which package groups to install
    install_essential: true
    install_development: true
    install_optional: false
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      tags: ['always']
    
    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
      tags: ['upgrade']
    
    - name: Install essential packages
      apt:
        name: "{{ essential_packages }}"
        state: present
      when: install_essential | bool
      tags: ['essential']
    
    - name: Install development packages
      apt:
        name: "{{ development_packages }}"
        state: present
      when: install_development | bool
      tags: ['development']
    
    - name: Install optional packages
      apt:
        name: "{{ optional_packages }}"
        state: present
      when: install_optional | bool
      tags: ['optional']

    - name: Remove deb managed chezmoi
      apt:
        name: chezmoi
        state: absent

    - name: Ensure snapd.socket is enabled and started
      ansible.builtin.systemd:
        name: snapd.socket
        enabled: true
        state: started

    - name: sandbox snaps
      community.general.snap:
        name: "{{ item }}"
        state: present
        channel: stable
      loop: "{{ snaps_sandbox | list }}"
    
    - name: classic snaps
      community.general.snap:
        name: "{{ item }}"
        state: present
        channel: stable
        classic: true
      loop: "{{ snaps_classic | list }}"

    - name: Clean up package cache
      apt:
        autoclean: yes
        autoremove: yes
      tags: ['cleanup']
